spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/mobile-server
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    contextPath: /mobile

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR